language: ruby
addons:
  apt:
    packages:
    - ruby-dev
    - libgsl0ldbl
    - libgsl0-dev
cache: bundler
rvm:
- 2.5
before_install:
- gem install bundler --no-document
before_script:
- bundle exec rake setup[https://${GH_TOKEN}@github.com/cat-in-136/cat-in-136.github.io.git]
script:
- bundle exec rake generate
- bundle exec rake validate
after_success:
- bundle exec rake -q deploy 2>&1 | sed "s/${GH_TOKEN}/\${GH_TOKEN}/g"
env:
  global:
  - GIT_COMMITTER_NAME="cat_in_136 (via Travis-CI)"
  - GIT_COMMITTER_EMAIL="cat.in.136+github@gmail.com"
  - GIT_AUTHOR_NAME="cat_in_136 (via Travis-CI)"
  - GIT_AUTHOR_EMAIL="cat.in.136+github@gmail.com"
notifications:
  email: false
  slack:
    secure: GdzbyI8jOePrgGqVnFxCe2rZvSVVFg7Uh9gcD1u1AUSq0LjzHu7UotuSUOfFbh+uL7+ON8JKzRe/lDt9sQETVh5InIigoQ5syQ3dbzlrbf7i0wbIMvncPADri68eLNOSqH6lCPtBP/bO1tS1tFE6rhKTNqWbULDoSHeljPI0JcU=
