# Site settings
title: cat_in_136.blog()
baseurl: ""
url: "https://cat-in-136.github.io"

exclude:
 - Gemfile
 - Gemfile.lock
 - Rakefile
 - README.md
 - vendor

paginate: 10
paginate_path: "/page:num"

timezone: Japan
encoding: utf-8
#safe: true
#lsi: true
sass:
        style: :compact

gems:
 - jekyll-paginate

# Build settings
#markdown: kramdown
#permalink: pretty
permalink: /:year/:month/:title.html


twitter_username: cat_in_136
github_username: cat-in-136
source_repo_name: cat-in-136/blog
source_repo_branch: master
