name: Build Blog

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        path: ./_deploy
        repository: cat-in-136/cat-in-136.github.io
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        persist-credentials: true

    - name: Install LAPACKE and OpenBLAS
      run: sudo apt-get install liblapacke-dev libopenblas-dev -y
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Generate document
      run: bundle exec rake generate
    - name: Validate generated contents
      run: bundle exec rake validate

    - run: |
        rsync -a --delete --exclude .git _site/ _deploy/
        cd _deploy
        [[ -f .nojekyll ]] || touch .nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        external_repository: cat-in-136/cat-in-136.github.io
        publish_branch: master
        publish_dir: ./_deploy
