name: Test of Building Blog

on:
  push:
    branches-ignore: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install LAPACKE and OpenBLAS
      run: sudo apt-get install liblapacke-dev libopenblas-dev -y
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Generate document
      run: bundle exec rake generate
    - name: Validate generated contents
      run: bundle exec rake validate
